export const LOADING = 'LOADING';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_FORM_ERROR = 'RECEIVE_FORM_ERROR';
export const RECEIVE_FORM_SUCCESS = 'RECEIVE_FORM_SUCCESS';
export const RESET_FORM_SUCCESS = 'RESET_FORM_SUCCESS';
